### ISSUE TITLE
ServiceNotFoundException

### ISSUE THREAD

**Issue by quentin-st** [irozgar/gulp-rev-versions-bundle#9]
Hi,

I'm running Symfony 3.1. I followed the instructions in the README, but stumble upon the following exception when running `server:run`:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                             
The service "assets.packages" has a dependency on a non-existent service "irozgar_gulp_rev_versions.asset.gulp_rev_version_strategy". 
```

I tried registering this service in my own `services.yml`: `server:run` succeeds, but then I get a `An exception has been thrown during the rendering of a template ("The file "assets/css/lib.css" does not exist and there is no version file for it") in AppBundle::base.html.twig at line 45.` exception.

```
services:
    irozgar_gulp_rev_versions.asset.gulp_rev_version_strategy:
        class: Irozgar\GulpRevVersionsBundle\Asset\GulpRevVersionStrategy
        arguments:
            - "%kernel.root_dir%"
            - "%gulp_rev_manifest_path%"
```

> Note: after a bit of debugging, I found that your bundle handles framework bundle's assets, but not mine
